services:
  basibasaubackend:
    container_name: basibasaubackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - POSTGRES_URL=postgresql://admin:root@basibasaupostgres:5432/basibasau
    env_file:
      - ./backend/.env
    networks:
      - basibasaunetwork
    depends_on:
      - basibasaupostgres
      - basibasauredis
    volumes:
      - ./backend:/home/basibasau
      - /home/basibasau/node_modules
    command: npm run dev

  basibasauclient:
    container_name: basibasauclient
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://basibasaubackend:5000/api/v1
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
    ports:
      - 3000:3000
    depends_on:
      - basibasaubackend
    networks:
      - basibasaunetwork
    volumes:
      - ./client:/home/basibasau
      - /home/basibasau/node_modules
    command: npm run dev

  basibasaupostgres:
    container_name: basibasaupostgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST: basibasaupostgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: basibasau
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basibasaunetwork

  basibasauredis:
    container_name: basibasauredis
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - basibasaunetwork

  adminerbasibasau:
    container_name: adminerbasibasau
    image: adminer:5
    environment:
      ADMINER_DEFAULT_SERVER: basibasaupostgres
    restart: unless-stopped
    networks:
      - basibasaunetwork
    ports:
      - 8080:8080
    depends_on:
      - basibasaupostgres

volumes:
  postgres_data:

networks:
  basibasaunetwork:
